version = "3.7.17"

runner.dialect = scala3

maxColumn = 100

align.preset = more
align.openParenCallSite = true
align.openParenDefnSite = true

newlines.beforeCurlyLambdaParams = true

rewrite.rules = [
  SortImports,
  RedundantBraces,
  RedundantParens
]

spaces.inImportCurlyBraces = true

danglingParentheses.preset = true

docstrings.style = keep
